Replaced gql syntax with tql syntax to provide highlighting for all TypeQL keywords
typedb-osi/typeql-plugin-vscode pull request #1
Opened 2021-06-14 00:13 UTC by FuzzyCoder

Also rebranded everything to TypeDB/TypeQL

2021-06-24 11:00 UTC, alexjpwalker requested changes
Looks good against a few query types I've tried! I've requested some small changes.

2021-06-24 11:00 UTC, alexjpwalker commented on README.md
> +Syntax highliter for TypeQL
```suggestion
Syntax highlighter for TypeQL
```

2021-06-24 11:00 UTC, alexjpwalker commented on grammar/TypeQL.g4
> +/*
Let's revert the formatting of this file to make its content **precisely** identical to https://github.com/vaticle/typeql/blob/master/grammar/TypeQL.g4. This makes it easier to verify that the grammar is up-to-date.

![image](https://user-images.githubusercontent.com/14253102/123248935-60feb480-d4e0-11eb-8701-227a0a4c9af4.png)

2021-06-24 11:00 UTC, alexjpwalker commented on package.json
> +                    "TypeDB",
```suggestion
                    "TypeQL",
```

2021-06-24 11:00 UTC, alexjpwalker commented on syntaxes/.vsixmanifest
> +    <Tags>tql, typedb, typeql, gql,graql,grakn,Graql,__ext_gql</Tags>
We have permanently abandoned the "Grakn" and "Graql" monikers so they shouldn't be referenced anywhere
```suggestion
    <Tags>tql, typedb, typeql, __ext_tql</Tags>
```

2021-06-26 02:06 UTC, FuzzyCoder commented on grammar/TypeQL.g4
> +/*
Alex - perhaps this file should not even be in this repo as the single source of truth should be https://github.com/vaticle/typeql/blob/master/grammar/TypeQL.g4.  Thoughts?

2021-06-28 08:38 UTC, alexjpwalker commented on grammar/TypeQL.g4
> +/*
Yeah I agree, if this repo doesn't use this file then it shouldn't be here 👍

2021-06-28 08:40 UTC, alexjpwalker approved these changes

2021-06-28 16:38 UTC, merged